/**
 * FundLens v6 — Fund Detail Inline Expansion
 *
 * Replaces the 420px slide-in sidebar with an inline row expansion
 * in the Portfolio fund table. Click a fund row → expands below to
 * show holdings grouped by sector (v5.1 drill-in pattern).
 *
 * No sidebar, no backdrop, no overlay. Just expands in place.
 *
 * Session 12 rewrite. Destination: client/src/components/FundDetail.tsx
 */

import { useEffect, useState, useMemo } from 'react';
import { fetchFundScore, type FundScore, type Fund } from '../api';
import { theme } from '../theme';

// ─── Types ──────────────────────────────────────────────────────────────────

interface Holding {
  name: string;
  ticker: string | null;
  pct_of_nav: number;
  sector: string | null;
}

interface Props {
  ticker: string;
  onClose: () => void;
}

// ─── Sector Colors ──────────────────────────────────────────────────────────

const SECTOR_COLORS: Record<string, string> = {
  Technology: '#3b82f6', Healthcare: '#06b6d4', Financials: '#8b5cf6',
  'Consumer Discretionary': '#f59e0b', 'Consumer Staples': '#22c55e',
  Energy: '#ef4444', Industrials: '#f97316', Materials: '#14b8a6',
  'Real Estate': '#ec4899', Utilities: '#6366f1',
  'Communication Services': '#a855f7', 'Precious Metals': '#eab308',
  'Fixed Income': '#64748b', 'Cash & Equivalents': '#94a3b8',
  Other: '#71717a',
};

function getSectorColor(sector: string): string {
  return SECTOR_COLORS[sector] ?? '#71717a';
}

// ─── Main Component ─────────────────────────────────────────────────────────

export function FundDetail({ ticker, onClose }: Props) {
  const [_fund, setFund] = useState<Fund | null>(null);
  const [_score, setScore] = useState<FundScore | null>(null);
  const [holdings, setHoldings] = useState<Holding[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [expandedSector, setExpandedSector] = useState<string | null>(null);

  useEffect(() => {
    setLoading(true);
    setError(null);
    setExpandedSector(null);

    fetchFundScore(ticker).then((res) => {
      if (res.error) {
        setError(res.error);
      } else if (res.data) {
        setFund(res.data.fund);
        setScore(res.data.score);
        setHoldings((res.data.holdings || []) as Holding[]);
      }
      setLoading(false);
    });
  }, [ticker]);

  // Group holdings by sector
  const sectorGroups = useMemo(() => {
    const map = new Map<string, { weight: number; items: Holding[] }>();
    for (const h of holdings) {
      const sector = h.sector || 'Other';
      const existing = map.get(sector) || { weight: 0, items: [] };
      existing.weight += h.pct_of_nav || 0;
      existing.items.push(h);
      map.set(sector, existing);
    }
    return [...map.entries()]
      .sort((a, b) => b[1].weight - a[1].weight)
      .map(([sector, data]) => ({
        sector,
        weight: data.weight,
        items: data.items.sort((a, b) => (b.pct_of_nav || 0) - (a.pct_of_nav || 0)),
        color: getSectorColor(sector),
      }));
  }, [holdings]);

  const totalWeight = sectorGroups.reduce((s, g) => s + g.weight, 0);

  // Extract natural-language summary from factor_details (generated by Claude Haiku)
  const summary = useMemo(() => {
    if (!_score?.factor_details) return null;
    const d = _score.factor_details as Record<string, unknown>;
    return typeof d.summary === 'string' ? d.summary : null;
  }, [_score]);

  // ─── Loading / Error ──────────────────────────────────────────────────

  if (loading) {
    return (
      <tr>
        <td colSpan={7} style={{ padding: '16px 20px', color: theme.colors.textDim, fontSize: 12 }}>
          Loading holdings for {ticker}…
        </td>
      </tr>
    );
  }

  if (error) {
    return (
      <tr>
        <td colSpan={7} style={{ padding: '16px 20px', color: theme.colors.error, fontSize: 12 }}>
          {error}
        </td>
      </tr>
    );
  }

  if (holdings.length === 0) {
    return (
      <tr>
        <td colSpan={7} style={{ padding: '16px 20px', color: theme.colors.textDim, fontSize: 12 }}>
          No holdings data available for {ticker}.
        </td>
      </tr>
    );
  }

  // ─── Inline expansion: sector groups with expandable holdings ──────────

  return (
    <tr>
      <td colSpan={7} style={{ padding: 0 }}>
        <div style={{
          background: theme.colors.surfaceAlt || '#1c1e23',
          borderTop: `1px solid ${theme.colors.border}`,
          borderBottom: `1px solid ${theme.colors.border}`,
          padding: '12px 20px 16px',
        }}>
          {/* Header row: title + close */}
          <div style={{
            display: 'flex', justifyContent: 'space-between', alignItems: 'center',
            marginBottom: 10,
          }}>
            <span style={{
              fontSize: 11, fontWeight: 700, textTransform: 'uppercase',
              letterSpacing: '0.08em', color: theme.colors.textDim,
            }}>
              Holdings by Sector — {holdings.length} positions
            </span>
            <button
              onClick={(e) => { e.stopPropagation(); onClose(); }}
              style={{
                background: 'none', border: 'none', color: theme.colors.textDim,
                cursor: 'pointer', fontSize: 16, padding: '0 4px', lineHeight: 1,
              }}
            >
              ×
            </button>
          </div>

          {/* Fund summary (editorial voice, from pipeline) */}
          {summary && (
            <p style={{
              fontSize: 13, lineHeight: 1.6, color: '#d1d5db',
              margin: '0 0 12px', padding: '0 4px',
            }}>
              {summary}
            </p>
          )}

          {/* Sector rows */}
          {sectorGroups.map(group => {
            const isExpanded = expandedSector === group.sector;
            const pct = totalWeight > 0 ? ((group.weight / totalWeight) * 100).toFixed(1) : '0';

            return (
              <div key={group.sector}>
                {/* Sector header row */}
                <div
                  onClick={(e) => {
                    e.stopPropagation();
                    setExpandedSector(prev => prev === group.sector ? null : group.sector);
                  }}
                  style={{
                    display: 'flex', alignItems: 'center', gap: 8,
                    padding: '6px 4px', cursor: 'pointer', borderRadius: 4,
                    transition: 'background 100ms',
                    background: isExpanded ? 'rgba(255,255,255,0.03)' : 'transparent',
                  }}
                >
                  {/* Color dot */}
                  <div style={{
                    width: 8, height: 8, borderRadius: 2,
                    background: group.color, flexShrink: 0,
                  }} />
                  {/* Sector name */}
                  <span style={{ fontSize: 13, color: theme.colors.text, flex: 1 }}>
                    {group.sector}
                  </span>
                  {/* Weight bar */}
                  <div style={{
                    width: 60, height: 4, borderRadius: 2,
                    background: theme.colors.border, overflow: 'hidden', flexShrink: 0,
                  }}>
                    <div style={{
                      height: '100%', borderRadius: 2,
                      background: group.color,
                      width: `${Math.min(100, parseFloat(pct))}%`,
                    }} />
                  </div>
                  {/* Percentage */}
                  <span style={{
                    fontFamily: theme.fonts.mono, fontSize: 12,
                    color: theme.colors.textMuted, minWidth: 40, textAlign: 'right',
                  }}>
                    {pct}%
                  </span>
                  {/* Expand arrow */}
                  <span style={{ fontSize: 11, color: theme.colors.textDim, width: 12, textAlign: 'center' }}>
                    {isExpanded ? '\u25BE' : '\u25B8'}
                  </span>
                </div>

                {/* Expanded holdings list */}
                {isExpanded && (
                  <div style={{
                    marginLeft: 16, marginBottom: 4,
                    borderLeft: `2px solid ${group.color}44`,
                    paddingLeft: 10,
                  }}>
                    {group.items.map((h, idx) => {
                      const name = h.name ?? '—';
                      const holdingTicker = h.ticker ?? null;
                      // pct_of_nav is in whole-percent units (4.89 = 4.89%), not fraction
                      const wt = h.pct_of_nav != null ? `${h.pct_of_nav.toFixed(2)}%` : '—';
                      return (
                        <div key={idx} style={{
                          display: 'flex', justifyContent: 'space-between',
                          alignItems: 'center', padding: '3px 0', fontSize: 12, gap: 8,
                          borderBottom: idx < group.items.length - 1 ? `1px solid ${theme.colors.border}33` : 'none',
                        }}>
                          <span style={{
                            color: '#cbd5e1', flex: 1,
                            overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap',
                          }}>
                            {name}
                          </span>
                          {holdingTicker && (
                            <span style={{
                              fontFamily: theme.fonts.mono, color: theme.colors.textDim,
                              fontSize: 11, flexShrink: 0,
                            }}>
                              {holdingTicker}
                            </span>
                          )}
                          <span style={{
                            fontFamily: theme.fonts.mono, color: theme.colors.textMuted,
                            fontSize: 11, flexShrink: 0, minWidth: 48, textAlign: 'right',
                          }}>
                            {wt}
                          </span>
                        </div>
                      );
                    })}
                  </div>
                )}
              </div>
            );
          })}
        </div>
      </td>
    </tr>
  );
}
